Финальное задание 8го спринта
k-shef/java-kanban pull request #3
Opened 2024-08-19 23:33 UTC by k-shef

Финальная работа 8го спринта.

2024-08-19 23:38 UTC, k-shef commented
part 2

2024-08-19 23:43 UTC, k-shef commented
part4

2024-08-20 00:00 UTC, k-shef commented
part5

2024-08-20 00:08 UTC, k-shef commented
part6

2024-08-22 14:32 UTC, mikita95 requested changes
Все сделано отлично  :) Оставил лишь небольшие рекомендации

2024-08-22 14:32 UTC, mikita95 commented on src/model/Epic.java
> +    public void updateDurationAndTime(List<Subtask> subtasks) {
Лучше было бы эту логику поместить в менеджер, а здесь оставить лишь простое хранение данных

2024-08-23 18:39 UTC, mikita95 approved these changes
Все отлично :) Можно мержить пул-реквест

2024-10-29 22:01 UTC, merged